export const registrationConfig = {
  // =======================================================================
  // IMPORTANT: DO NOT EXPOSE THE PRIVATE ADMIN EMAIL HERE.
  // The private email (ydv.sumansh@gmail.com) is ONLY used to create the 
  // Google Sheet and the Google Apps Script. 
  // Paste the Web App URL generated by Google Apps Script below.
  // =======================================================================
  
  // Example: "https://script.google.com/macros/s/AKfycb.../exec"
  GOOGLE_APPS_SCRIPT_URL: "", 

};
